"""
Django settings for panel_admin project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

# panel_admin/settings.py
# ... al inicio ...
from datetime import timedelta # Añade esto

# ... en INSTALLED_APPS, añade esto:
INSTALLED_APPS = [
    # ...
    'django.contrib.admin',
    'django.contrib.auth',
    # ...
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'core', # Nuestra app
]

# ... en MIDDLEWARE, añade esto (¡importante el orden!):
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware', # Añadir CORS aquí
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # ...
]

# ... al final del archivo, añade esto:

# Configuración de DRF (Django Rest Framework)
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    )
}

# Configuración de JWT (JSON Web Tokens)
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60), # Tiempo de vida del token
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}

# Configuración de CORS (para permitir que el frontend hable con el backend)
# ¡MUY IMPORTANTE! Si usas Live Server, usa el puerto 5500.
CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:5500", # Puerto de Live Server (VS Code)
    "http://localhost:5500",
]