# Generated by Django 5.2.7 on 2025-10-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='activo',
            field=models.BooleanField(default=True, help_text='Bot activo o inactivo'),
        ),
        migrations.AddField(
            model_name='bot',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción del bot'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='notas',
            field=models.TextField(blank=True, help_text='Notas adicionales de la reserva'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('Confirmada', 'Confirmada'), ('Pendiente', 'Pendiente'), ('Cancelada', 'Cancelada')], default='Confirmada', max_length=20),
        ),
    ]
