# Generated by Django 5.2.7 on 2025-10-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bot_activo_bot_descripcion_reserva_notas_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bot',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Bot', 'verbose_name_plural': 'Bots'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['-fecha_registro'], 'verbose_name': 'Emprendimiento', 'verbose_name_plural': 'Emprendimientos'},
        ),
        migrations.AddField(
            model_name='bot',
            name='bloqueado',
            field=models.BooleanField(default=False, help_text='Bot bloqueado por el administrador'),
        ),
        migrations.AddField(
            model_name='bot',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bot',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de registro del emprendimiento', null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_ultimo_acceso',
            field=models.DateTimeField(blank=True, help_text='Fecha del último acceso al sistema', null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='max_bots_allowed',
            field=models.PositiveIntegerField(default=3, help_text='Cantidad máxima de bots que puede crear este emprendimiento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='notas_admin',
            field=models.TextField(blank=True, help_text='Notas del administrador sobre este emprendimiento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='status',
            field=models.CharField(choices=[('activo', 'Activo'), ('suspendido', 'Suspendido'), ('inactivo', 'Inactivo')], default='activo', help_text='Estado del emprendimiento', max_length=20),
        ),
    ]
